### ISSUE TITLE
Breaking changes from v0.1.3 to v2.0.0?

### ISSUE THREAD

**Issue by joelmukuthu** [iceddev/pg-connection-string#22]
Hi,

I'm using this module and looking to upgrade from 0.1.3 to 2.0.0 but can't determine what the breaking changes were. What were they?

Thanks,
Joel

**Comment by clayzermk1** [comment]
I'd like to second this request, and give this a bump since it's been ~6mo with no reply. Could a maintainer please update the release information?

**Comment by clayzermk1** [comment]
Thanks for maintaining this critical package!

Bumping the major was certainly a prudent thing to do.

From what I can see, there never was a 1.x release, only 0.x releases. `pg` itself is still using 0.1.3. The releases page doesn't show any releases between 0.1.3 and 2.0.0. semver.npmjs.com doesn't show any 1.x releases either.

Would you have time to review the 10 commits between 0.1.3 and 2.0.0, move up the "latest release" flag, and update the 2.0.0 release description with a summary of the changes? I looked them over in detail and they seem to be straightforward. I could even take a stab at a changelog draft in the issue here.

**Comment by hjr3** [comment]
https://github.com/iceddev/pg-connection-string/releases/tag/v2.0.0

Please review and let me know if I missed anything: https://github.com/iceddev/pg-connection-string/compare/v0.1.3...v2.0.0
